package nez.generator;

import nez.lang.And;
import nez.lang.AnyChar;
import nez.lang.ByteChar;
import nez.lang.ByteMap;
import nez.lang.Capture;
import nez.lang.Choice;
import nez.lang.Expression;
import nez.lang.Grammar;
import nez.lang.Link;
import nez.lang.New;
import nez.lang.NonTerminal;
import nez.lang.Not;
import nez.lang.Option;
import nez.lang.Production;
import nez.lang.Repetition;
import nez.lang.Repetition1;
import nez.lang.Replace;
import nez.lang.Sequence;
import nez.lang.Tagging;

public class PEGTLGenerator extends GrammarGenerator {

	@Override
	public String getDesc() {
		return "Parsing Expression Grammar Template Library for C++11";
	}

	@Override
	public void makeHeader(Grammar g) {
		L("// The following is generated by the Nez Grammar Generator ");
		L("#include<pegtl.hh>");

		for(Production p : g.getProductionList()) {
			L("struct " + _NonTerminal(p) + ";");
		}

	}

	@Override
	public void makeFooter(Grammar g) {

	}

	@Override
	protected String _NonTerminal(Production p) {
		return "p"
				+ p.getLocalName().replace("~", "_").replace("!", "NOT")
						.replace(".", "DOT");
	}

	@Override
	protected String _Open() {
		return "<";
	};

	@Override
	protected String _Close() {
		return ">";
	};

	@Override
	protected String _Delim() {
		return ",";
	};

	@Override
	public void visitGrouping(Expression e) {
		// W(_OpenGrouping());
		visitExpression(e);
		// W(_CloseGrouping());
	}

	@Override
	public void visitProduction(Production p) {
		Expression e = p.getExpression();
		L("struct " + _NonTerminal(p) + " : ");
		inc();
		L("");
		W("pegtl::seq<");
		visitExpression(e);
		W(", pegtl::success> {};");
		dec();
	}

	@Override
	public void visitEmpty(Expression e) {
		C("pegtl::success");
	}

	@Override
	public void visitFailure(Expression e) {
		C("pegtl::failure");
	}

	@Override
	public void visitNonTerminal(NonTerminal e) {
		W(_NonTerminal(e.getProduction()));
	}

	@Override
	public void visitByteChar(ByteChar e) {
		C("pegtl::one", e.byteChar);
	}

	@Override
	public void visitByteMap(ByteMap e) {
		C("pegtl::one", e.byteMap);
	}

	@Override
	public void visitString(String s) {
		int cnt = 0;
		W("pegtl::string").W(_Open());
		for(int c = 0; c < s.length(); c++) {
			if(cnt > 0) {
				W(_Delim());
			}
			W(String.valueOf((int)s.charAt(c)));
			cnt++;
		}
		W(_Close());
	}

	@Override
	public void visitAnyChar(AnyChar e) {
		W("pegtl::any");
	}

	@Override
	public void visitOption(Option e) {
		C("pegtl::opt", e);
	}

	@Override
	public void visitRepetition(Repetition e) {
		C("pegtl::star", e);
	}

	@Override
	public void visitRepetition1(Repetition1 e) {
		C("pegtl::plus", e);
	}

	@Override
	public void visitAnd(And e) {
		C("pegtl::at", e);
	}

	@Override
	public void visitNot(Not e) {
		C("pegtl::not_at", e);
	}

	@Override
	public void visitChoice(Choice e) {
		C("pegtl::sor", e);
	}

	@Override
	public void visitSequence(Sequence e) {
		W("pegtl::seq<");
		super.visitSequence(e);
		W(">");
	}

	@Override
	public void visitNew(New e) {
		W("pegtl::success");
		// if(e.lefted) {
		// C("LCapture", e.shift);
		// }
		// else {
		// C("NCapture", e.shift);
		// }
	}

	@Override
	public void visitCapture(Capture e) {
		W("pegtl::success");
		// C("Capture", e.shift);
	}

	@Override
	public void visitTagging(Tagging e) {
		W("pegtl::success");
		// C("Tagging", e.getTagName());
	}

	@Override
	public void visitReplace(Replace e) {
		W("pegtl::success");
		// C("Replace", StringUtils.quoteString('"', e.value, '"'));
	}

	@Override
	public void visitLink(Link e) {
		// if(e.index != -1) {
		// C("Link", String.valueOf(e.index), e);
		// }
		// else {
		// C("Link", e);
		// }
		visitExpression(e.get(0));
	}

	@Override
	public void visitUndefined(Expression e) {
		if(e.size() > 0) {
			visitExpression(e.get(0));
		}
		else {
			W("pegtl::success");
		}
		// W("<");
		// W(e.getPredicate());
		// for(Expression se : e) {
		// W(" ");
		// visit(se);
		// }
		// W(">");
	}

}
